// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apis

import (
	"github.com/go-playground/validator/v10"
	"net/http"
)

// Injectors from wire.go:

func CreateReqContext(request *http.Request) *ReqContext {
	validate := validator.New()
	reqContext := NewReqContext(validate, request)
	return reqContext
}
