// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package newauth

import (
	"github.com/PDC-Repository/newauth/newauth/apis"
	"github.com/PDC-Repository/newauth/newauth/services"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, error) {
	db := NewDatabase()
	mailService := services.NewMailService()
	userApi := apis.NewUserApi(db, mailService)
	teamApi := apis.NewTeamApi()
	router, err := NewRouter(db, userApi, teamApi)
	if err != nil {
		return nil, err
	}
	application := NewApplication(db, router)
	return application, nil
}
